# Follow this link: https://btholt.github.io/complete-intro-to-containers/more-complicated-nodejs-app

# Base image: node:latest
FROM node:latest
# Create a user called node
USER node
# Create app directory
RUN mkdir /home/node/code
# Set the working directory to /home/node/code
WORKDIR /home/node/code
# Copy server file local to the container
# Source . destination .

# COPY layer is created when the Dockerfile is built and it contains all the files in the context that are needed for the build.
# this layer is cached and will not be rebuilt unless the context changes.
COPY --chown=node:node package.json package-lock.json ./
# RUN npm install
#for example. It's faster and more secure than npm install. 
# npm ci it's very similar to npm install,
# but it's meant for automated builds,
# like in a CI/CD pipeline 
RUN npm ci
# Copy all the files from the current directory to the container
COPY --chown=node:node . .

# Expose port 3000
EXPOSE 3000
# RUN the command to start the app
CMD ["node", "index.js"]