#  Create a docker image for the nodejs app
# fetch the latest nodejs image from docker hub or local repo
FROM node:latest
# User to run the app
USER node
# Work directory
WORKDIR /home/node/code
# Copy source to destination
# COPY --chown=node:node index.js index.js

# Add 
ADD --chown=node:node index.js index.js
# Run the app
CMD ["node", "index.js"]